apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-venteregister
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /sokos-up-venteregister/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sokos-up-venteregister/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /sokos-up-venteregister/internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://utbetalingsportalen.intern.dev.nav.no/sokos-up-venteregister"
    - "https://utbetalingsportalen.ansatt.dev.nav.no/sokos-up-venteregister"
    - "https://utbetalingsportalen-qx.intern.dev.nav.no/sokos-up-venteregister"
    - "https://utbetalingsportalen-qx.ansatt.dev.nav.no/sokos-up-venteregister"

  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
